spring: # default test profile
  datasource:
    url: "jdbc:h2:mem:zzansuni;MODE=MySQL"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql.init.mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
logging.level:
  org.hibernate:
    orm.jdbc.bind: trace
    SQL: debug
---
spring:
  config:
    activate:
      on-profile: local, dev, prod # dev, prod 공통 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql.init.mode: never
  h2.console.enabled: false
---
spring: # local profile
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/zzansuni?createDatabaseIfNotExist=true
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: none
---
spring: # dev,prod profile
  config:
    activate:
      on-profile: dev, prod
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none