spring: # default test profile
  profiles:
    include:
      - flyway
      - database
      - jwt
      - oauth2
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      resolve-lazily: true # 파일 업로드 시점에 메모리에 저장
  lifecycle:
    timeout-per-shutdown-phase: 15s # 스프링이 종료될때 모든 작업이 종료될때 까지 기다리는 시간
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  use-fqn: true # 패키지 경로를 포함한 클래스명으로 문서화 (FOR inner static class)
server:
  shutdown: graceful
  tomcat:
    connection-timeout: 3s # 클라이언트와 서버 사이의 연결 시간 초과(TCP 연결 수락 후, 실제 HTTP 요청이 올 때까지의 시간)
    keep-alive-timeout: 15s # 클라이언트와 서버 사이의 keep-alive 시간 초과 (새로운 HTTP 요청이 올 때까지의 시간)
    threads:
      max: 50 # 최대 스레드 수(개발 환경에서는 50개로 설정)
      min-spare: 5 # 최소 스레드 수(개발 환경에서는 5개로 설정)
---
spring:
  config:
    activate:
      on-profile: local, dev, prod # dev, prod 공통 설정
server:
  tomcat:
    threads:
      max: 200 # 최대 스레드 수 (기본값 200)
      min-spare: 10 # 최소 스레드 수 (기본값 10)
---
spring: # dev,prod profile
  config:
    activate:
      on-profile: dev, prod
cloud:
  aws:
    s3.bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false