spring: # default test profile
  datasource:
    url: "jdbc:h2:mem:zzansuni;"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql.init.mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
logging.level:
  org.hibernate:
    orm.jdbc.bind: trace
    SQL: debug
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
jwt:
  secret: 4099a46b-39db-4860-a61b-2ae76ea24c43
  access-token-expire-time: 1800000 # 30 minutes
  refresh-token-expire-time: 2592000000 # 30 days
#cloud:
#  aws:
#    s3.bucket: zzansuni
#    credentials:
#      access-key: ${AWS_ACCESS_KEY}
#      secret-key: ${AWS_SECRET_KEY}
#    region:
#      static: ${AWS_REGION}
#      auto: false
#    stack:
#      auto: false
---
spring:
  config:
    activate:
      on-profile: dev, prod # dev, prod 공통 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2.console.enabled: false
jwt:
  secret: ${JWT_SECRET}
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
---
spring: # dev profile
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/zzansuni
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql.init.mode: always
---
spring: # prod profile
  config:
    activate:
      on-profile: prod